### ISSUE TITLE
Extend usability of Buckaxe

### ISSUE THREAD

**Issue by seedcard** [BeeEvolved/Buckaxe#1]
Hi just purchased my first bitaxe miner and love it!

Have been thinking how it would be possible to run on solar. In Europe most common commercial pv panels are 48v. 

For example I have a spare 48v 450w panel. Would love to find a safe way to link it to my bitaxe and mine sats when the sun shines. 

You would probably need to add extra functionality to only output 5v when the panel is generating. I would be worried about cycling on and off in the morning and evening when the conditions are marginal.

If this project is still active I would be happy to contribute towards costs.

**Comment by BeeEvolved** [comment]
Absolutely! That sounds exciting. The plan was to revisit the Buckaxe and another solar-focused Bitaxe project in spring 2025, when the weather is nicer in March. We could certainly prioritize it sooner, but as you can see, we have many ongoing projects and need to focus our efforts and resources. That said, we’d be happy to revisit the Buckaxe earlier if additional resources become available.
